### ISSUE TITLE
unable to build blink

### ISSUE THREAD

**Issue by quantrpeter** [wuxx/icesugar-pro#12]
Hi

3.51. Executing JSON backend.
ERROR: Module rst_gen contains processes, which are not supported by JSON backend (run `proc` first).
make: *** [Makefile:9: blink.json] Error 1

thanks
Peter

**Comment by ngzh** [comment]
As for yosys-0.16, you may try
```
$(TARGET).json: $(OBJS)
   -- yosys -p "synth_ecp5 json $@" $(OBJS)
   ++ yosys -p "read_verilog $(OBJS); synth_ecp5 -json $@"
```
For detail,  https://github.com/YosysHQ/yosys/issues/3109#issuecomment-996261025

**Comment by quantrpeter** [comment]
thanks
