### ISSUE TITLE
TDO check error at line 10

### ISSUE THREAD

**Issue by Chandler-Kluser** [wuxx/icesugar-pro#17]
I am trying to flash a simple nand project to my icesugar-pro with ext board using the USB-C DAPLink programmer.

I have successfully compiled `openocd` and added `dapprog` in my user `PATH` variable.

but when I try to flash using `dapprog`, it gets a TDO error:
```
$ dapprog top.bit                          
EXT: bit
TARGET: top_flash.svf
[sudo] senha para chandler: 
Open On-Chip Debugger 0.12.0-rc2+dev-00962-g12ce17094 (2022-10-28-13:16)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
DEPRECATED! use 'adapter speed' not 'adapter_khz'
Info : CMSIS-DAP: SWD supported
Info : CMSIS-DAP: JTAG supported
Info : CMSIS-DAP: Atomic commands supported
Info : CMSIS-DAP: FW Version = 0254
Info : CMSIS-DAP: Serial# = 07000001002400614d0000164e514137a5a5a5a597969908
Info : CMSIS-DAP: Interface Initialised (JTAG)
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 1 TDO = 1 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 10000 kHz
Info : cmsis-dap JTAG TLR_RESET
Info : cmsis-dap JTAG TLR_RESET
Error: JTAG scan chain interrogation failed: all ones
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: ecp5.tap: IR capture error; saw 0xff not 0x1
Info : cmsis-dap JTAG TLR_RESET
Warn : Bypassing JTAG setup events due to errors
Warn : gdb services need one or more targets defined
svf processing file: "top_flash.svf"
5%    Info : cmsis-dap JTAG TLR_RESET
Info : cmsis-dap JTAG TLR_RESET
Info : cmsis-dap JTAG TLR_RESET
Error: tdo check error at line 10
Error:     READ = 0xffffffff
Error:     WANT = 0x41111043
Error:     MASK = 0xffffffff
Error: fail to run command at line 2137
Error: tdo check error at line 10
Error:     READ = 0xffffffff
Error:     WANT = 0x41111043
Error:     MASK = 0xffffffff
Time used: 0m7s818ms 
svf file programmed failed
```

I have tried also to drag and drop the bitstream file to DAPLINK in File Manager, I tried also to flash using `icesprog` but nothing seems to be working.

I actually see the red led blinking from DAP chip in ext board when a run the flash program, but the FPGA itself remains with the older project.

Can someone help me?

Thanks in advance!

**Comment by wuxx** [comment]
hello, do you use the on-board iCELink(based on DAPLink), or you connect a external DAPLink?

**Comment by Chandler-Kluser** [comment]
I have connected DAPLink from the external dock board (that green one sold in aliexpress)

**Comment by wuxx** [comment]
if you use icesugar-pro board, you should connect the module on-board USB for download, not the usb of dock board

**Comment by Chandler-Kluser** [comment]
I know that, but to avoid replacing the core board in the dock every flash time, It should be supposed to support flash through DAPLink dock board, right?

**Comment by wuxx** [comment]
why you need to replacing the core board every time ?
actually the dock board is first design for this board
https://github.com/wuxx/Colorlight-FPGA-Projects

**Comment by Chandler-Kluser** [comment]
this is in fact the dock board I am using.

the usb cable doesn't fit the core board when it is attached to the dock board, so it is necessary to unplug from the dock, flash the bitstream and plug it back

**Comment by wuxx** [comment]
It is recommended that you use another USB cable. At present, no customer has reported similar problems. The download can only be done through the USB of the module.

**Comment by Chandler-Kluser** [comment]
Thanks a lot for your attention, I will use only the USB core port to flash the FPGA.

Closing the issue!!
