### ISSUE TITLE
Getting junk in terminal with linux-litex configuration

### ISSUE THREAD

**Issue by nihirash** [wuxx/icesugar-pro#2]
I'm macOS user and using minicom as uart-terminal(I've used in other case - everything was fine in other cases, configuring FPGA messages are fine). 

But when I've tried linux litex I've got this

<img width="858" alt="Снимок экрана 2021-05-19 в 22 02 56" src="https://user-images.githubusercontent.com/5459892/118869445-1476f680-b8ee-11eb-9d0c-6f66bc88fb70.png">

Port speed as specified in readme file. 
Is there issue cause configuration was ported from other board where clock was different? 

It isn't most important thing for this board but I'd like check samples. 

P.S. thank you for your boards. I have iCESugar 1.5 and Pro(now) both and they're great for me

**Comment by wuxx** [comment]
hello, do you test with icesugar-pro ? the clock is from on-board 25MHz osc.

**Comment by nihirash** [comment]
Yep, with icesugar-pro. 

Possibly it's macOS issue - I'll try check it soon and report you. 

Programmer debug messages receiving fine, other uart enabled examples working fine too - only linux-enabled configuration have issues.

**Comment by nihirash** [comment]
I've checked it and it's macOS issue(I've tried on M1 mac). 

You can't setup uart to 1000000 baud.
