### ISSUE TITLE
iCELink open fail!

### ISSUE THREAD

**Issue by rizwan-isa** [wuxx/icesugar-pro#21]
I have ICESugar Pro 1.3 with colourlight expansion board.

I installed icesprog to read/write to the fpga. at first this was working. and now this doesnt work anymore and says "iCELink open fail!" 

I can drag and drop bit stream files on to the drive to program. However, I would like to debug also with the usb on the expansion board: <img width="240" alt="ice with expansion" src="https://user-images.githubusercontent.com/100386408/217778299-04f31a89-86a3-4159-bd50-2aa4774df6c6.png">

<img width="674" alt="cmd ice" src="https://user-images.githubusercontent.com/100386408/217778736-00c02b01-c975-49ef-93f7-ee31488ee196.png">
<img width="965" alt="daplink" src="https://user-images.githubusercontent.com/100386408/217778744-4bbd1a6b-5fa1-49f5-959e-4e6e9a1ebe2a.png">

**Comment by wuxx** [comment]
hello，you need to use the TYPE-C USB on module for download

**Comment by rizwan-isa** [comment]
with that method I am able to drag and drop bit files and program the device. However, I still cant open iCELink on icesprog

**Comment by wuxx** [comment]
try add sudo before icesprog

**Comment by rizwan-isa** [comment]
will the command work under WLS? https://ubuntu.com/wsl

**Comment by rizwan-isa** [comment]
How do I install icesprog under linux?

**Comment by wuxx** [comment]
can get the source code and the binary here
https://github.com/wuxx/icesugar/tree/master/tools

**Comment by rizwan-isa** [comment]
Thank you not a linux guy. how do I install them and start using it. I have ubuntu image on VM installed with all the dependencies

**Comment by wuxx** [comment]
$/path/to/the/icesprog xxx.bin
you can also export the path, and just use
$icesprog xxx.bin

**Comment by rizwan-isa** [comment]
runnning 64 bit linux do I rename this file [icesprog.x64.linux](https://github.com/wuxx/icesugar/blob/master/tools/icesprog.x64.linux)

**Comment by rizwan-isa** [comment]
ok i managed to do it using this command 

./icesprog.x64.linux

**Comment by Chandler-Kluser** [comment]
I am facing the same issue here, but this time adding user in dialout group or running `icesprog` as root is not working...

Here you will find more details:
![image](https://github.com/wuxx/icesugar-pro/assets/29960960/276b8204-1594-4e9c-b111-c66265b3f55a)

I can only flash using the drag and drop feature of the onboard debugger, but I cannot program with `icesprog` using the dock USB type C:

![IMG_20230610_022243879](https://github.com/wuxx/icesugar-pro/assets/29960960/b33d61d0-fd26-419b-bfe4-41e74ec0ec5f)

It is annoying everytime I want to flash the FPGA I have to detach it from the dock USB to the onboard USB Type C because the cable does not fit without removing the core board from the dock...

Can you help me with it?

**Comment by wuxx** [comment]
hello, you need to use the TYPE-C USB on module, the USB on ExtBoard only has power supply function

**Comment by Chandler-Kluser** [comment]
This is so frustrating, but thank you a lot for the information!

**Comment by wdevore** [comment]
I have the icesugar 1.5. I run linux Pop_OS!. To get iCELink to run "icesprog -r" I needed to add a udev rule as a **USB subsystem** under */etc/udev* in a *.rules* file:
```
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="1d50", ATTRS{idProduct}=="602b", MODE="0660", GROUP="plugdev", TAG+="uaccess"
```

You don't need to reboot. Just issue a reload and trigger:
```
$ sudo udevadm control --reload-rules
$ sudo udevadm trigger
```
Then you can run icesprog:
```
$ icesprog -r
flash offset: 0x00000000
read flash (0 (0x0) Bytes)
use -l to set read len
```

**Comment by ZhangPeterGree** [comment]
https://github.com/FPGAwars/apio/wiki/Quick-start#apio-installation
Just install APIO. Follow below.
pip install apio
apio install -a
apio drivers --ftdi-enable

reboot
