### ISSUE TITLE
DDR vs DDR2

### ISSUE THREAD

**Issue by jeremysee2** [wuxx/icesugar-pro#3]
I believe that this board is compatible with the SODIMM-DDR2-200P socket, not DDR as mentioned in the README.md

**Comment by jeremysee2** [comment]
The difference is in the position of the key at the board edge, it's slightly different and not immediately obvious, to those designing for it with custom boards

**Comment by wuxx** [comment]
yes, you are right, thanks for the advice, will update the README.md
