### ISSUE TITLE
FPGA pin error when connecting SPI-Flash

### ISSUE THREAD

**Issue by yodalee** [wuxx/icesugar-pro#6]
Can FPGA in icesugar-pro communicates with SPI-Flash and get data stored inside? I want to put some binary code inside to let FPGA execute it.
According to the schematic pdf, I set lpf file as below:
```conf
# SPI-FLASH
LOCATE COMP "flash_cs"   SITE "N8";
LOCATE COMP "flash_mosi" SITE "T8";
LOCATE COMP "flash_miso" SITE "T7";
LOCATE COMP "flash_io2"  SITE "M7";
LOCATE COMP "flash_io3"  SITE "N7";
LOCATE COMP "flash_clk"  SITE "N9";

IOBUF PORT "flash_cs"   IO_TYPE=LVCMOS33 DRIVE=4;
IOBUF PORT "flash_clk"  IO_TYPE=LVCMOS33 DRIVE=4;
IOBUF PORT "flash_mosi" IO_TYPE=LVCMOS33 DRIVE=4;
IOBUF PORT "flash_miso" IO_TYPE=LVCMOS33 DRIVE=4;
IOBUF PORT "flash_io2"  IO_TYPE=LVCMOS33 DRIVE=4;
IOBUF PORT "flash_io3"  IO_TYPE=LVCMOS33 DRIVE=4;
```
However when compiling with nextpnr-ecp5:
```bash
nextpnr-ecp5 --25k --package CABGA256 --speed 6 --json top.json --textcfg top_out.config --lpf top.lpf
```
it will report error of:
```txt
ERROR: IO pin 'flash_clk$tr_io' constrained to pin 'N9', which does not exist for package 'CABGA256'.
ERROR: Packing design failed.
```
Is there any problem with this setting?

**Comment by wuxx** [comment]
I think it may be nextpnr-ecp5 don't support for free use of these pins

**Comment by yodalee** [comment]
Hmm, I see. Let me try other toolchain and see if it is a problem in toolchain. Otherwise I will have to use sdcard to store the source.

**Comment by yodalee** [comment]
I just check the [project trellis database](https://github.com/YosysHQ/prjtrellis-db/tree/master/ECP5). The port N9 do not exist in io json file of LFE5U-25F. I think I will try to use sdcard as an alternative. In the same time, can you check that schematic is correct or not?

**Comment by wuxx** [comment]
the schematic is correct, you can check the schematic of ulx3s or colorlight 5a-75b to confirm.

**Comment by yodalee** [comment]
I see. I will switch to sdcard then.
