### ISSUE TITLE
Is this board support diamond?

### ISSUE THREAD

**Issue by quantrpeter** [wuxx/icesugar-pro#9]
Is this board support diamond? I got

![image](https://user-images.githubusercontent.com/50471577/155850173-a71a0438-cd71-4955-a73b-7400d7fc1a00.png)

**Comment by wuxx** [comment]
the on-board debugger is implement by ourself, so it won't be supported by diamond, but you can use diamond to code, and when need to program, use the drag-and-drop or use the cmd tool icesprog.

**Comment by quantrpeter** [comment]
Oh yes, that what i am doing, thanks
